"""Language-scoped built-in AI prompt defaults.

Each target language owns its vocab and grammar prompts in a dedicated module.
"""

from .japanese import *  # noqa: F403
from .chinese import *  # noqa: F403
from .korean import *  # noqa: F403
from .english import *  # noqa: F403
from .japanese import (
    _JAPANESE_JSON_TEMPLATE, _JAPANESE_SYSTEM_PROMPT,
    _JAPANESE_JSON_TEMPLATE_EN, _JAPANESE_SYSTEM_PROMPT_EN,
    _JAPANESE_GRAMMAR_JSON_TEMPLATE, _JAPANESE_GRAMMAR_SYSTEM_PROMPT,
    _JAPANESE_GRAMMAR_JSON_TEMPLATE_EN, _JAPANESE_GRAMMAR_SYSTEM_PROMPT_EN,
)
from .chinese import (
    _CHINESE_JSON_TEMPLATE, _CHINESE_SYSTEM_PROMPT,
    _CHINESE_JSON_TEMPLATE_EN, _CHINESE_SYSTEM_PROMPT_EN,
    _CHINESE_GRAMMAR_JSON_TEMPLATE, _CHINESE_GRAMMAR_SYSTEM_PROMPT,
    _CHINESE_GRAMMAR_JSON_TEMPLATE_EN, _CHINESE_GRAMMAR_SYSTEM_PROMPT_EN,
)
from .korean import (
    _KOREAN_JSON_TEMPLATE, _KOREAN_SYSTEM_PROMPT,
    _KOREAN_JSON_TEMPLATE_EN, _KOREAN_SYSTEM_PROMPT_EN,
    _KOREAN_GRAMMAR_JSON_TEMPLATE, _KOREAN_GRAMMAR_SYSTEM_PROMPT,
    _KOREAN_GRAMMAR_JSON_TEMPLATE_EN, _KOREAN_GRAMMAR_SYSTEM_PROMPT_EN,
)
from .english import (
    _ENGLISH_JSON_TEMPLATE, _ENGLISH_SYSTEM_PROMPT,
    _ENGLISH_JSON_TEMPLATE_EN, _ENGLISH_SYSTEM_PROMPT_EN,
    _ENGLISH_GRAMMAR_JSON_TEMPLATE, _ENGLISH_GRAMMAR_SYSTEM_PROMPT,
    _ENGLISH_GRAMMAR_JSON_TEMPLATE_EN, _ENGLISH_GRAMMAR_SYSTEM_PROMPT_EN,
)
from .collocation import (
    _COLLOCATION_JSON_TEMPLATES, _COLLOCATION_SYSTEM_PROMPTS,
    _COLLOCATION_JSON_TEMPLATES_EN, _COLLOCATION_SYSTEM_PROMPTS_EN,
)
_SYSTEM_PROMPTS = {
    "japanese": _JAPANESE_SYSTEM_PROMPT,
    "chinese": _CHINESE_SYSTEM_PROMPT,
    "korean": _KOREAN_SYSTEM_PROMPT,
    "english": _ENGLISH_SYSTEM_PROMPT,
}
_JSON_TEMPLATES = {
    "japanese": _JAPANESE_JSON_TEMPLATE,
    "chinese": _CHINESE_JSON_TEMPLATE,
    "korean": _KOREAN_JSON_TEMPLATE,
    "english": _ENGLISH_JSON_TEMPLATE,
}
_SYSTEM_PROMPTS_EN = {
    "japanese": _JAPANESE_SYSTEM_PROMPT_EN,
    "chinese": _CHINESE_SYSTEM_PROMPT_EN,
    "korean": _KOREAN_SYSTEM_PROMPT_EN,
    "english": _ENGLISH_SYSTEM_PROMPT_EN,
}
_JSON_TEMPLATES_EN = {
    "japanese": _JAPANESE_JSON_TEMPLATE_EN,
    "chinese": _CHINESE_JSON_TEMPLATE_EN,
    "korean": _KOREAN_JSON_TEMPLATE_EN,
    "english": _ENGLISH_JSON_TEMPLATE_EN,
}
_GRAMMAR_SYSTEM_PROMPTS = {
    "japanese": _JAPANESE_GRAMMAR_SYSTEM_PROMPT,
    "chinese": _CHINESE_GRAMMAR_SYSTEM_PROMPT,
    "korean": _KOREAN_GRAMMAR_SYSTEM_PROMPT,
    "english": _ENGLISH_GRAMMAR_SYSTEM_PROMPT,
}
_GRAMMAR_JSON_TEMPLATES = {
    "japanese": _JAPANESE_GRAMMAR_JSON_TEMPLATE,
    "chinese": _CHINESE_GRAMMAR_JSON_TEMPLATE,
    "korean": _KOREAN_GRAMMAR_JSON_TEMPLATE,
    "english": _ENGLISH_GRAMMAR_JSON_TEMPLATE,
}
_GRAMMAR_SYSTEM_PROMPTS_EN = {
    "japanese": _JAPANESE_GRAMMAR_SYSTEM_PROMPT_EN,
    "chinese": _CHINESE_GRAMMAR_SYSTEM_PROMPT_EN,
    "korean": _KOREAN_GRAMMAR_SYSTEM_PROMPT_EN,
    "english": _ENGLISH_GRAMMAR_SYSTEM_PROMPT_EN,
}
_GRAMMAR_JSON_TEMPLATES_EN = {
    "japanese": _JAPANESE_GRAMMAR_JSON_TEMPLATE_EN,
    "chinese": _CHINESE_GRAMMAR_JSON_TEMPLATE_EN,
    "korean": _KOREAN_GRAMMAR_JSON_TEMPLATE_EN,
    "english": _ENGLISH_GRAMMAR_JSON_TEMPLATE_EN,
}


__all__ = [name for name in globals() if name.startswith("_") and not name.startswith("__")]
