"""Compatibility facade for built-in AI prompt and JSON-schema defaults.

Language-specific prompt data lives in :mod:`utils.prompts`; runtime overrides
remain owned by :mod:`utils.prompt_config`.
"""

from .prompts import (
    _CHINESE_JSON_TEMPLATE,
    _CHINESE_SYSTEM_PROMPT,
    _JAPANESE_JSON_TEMPLATE,
    _JAPANESE_SYSTEM_PROMPT,
    _KOREAN_JSON_TEMPLATE,
    _KOREAN_SYSTEM_PROMPT,
    _ENGLISH_JSON_TEMPLATE,
    _ENGLISH_SYSTEM_PROMPT,
    _JAPANESE_JSON_TEMPLATE_EN,
    _JAPANESE_SYSTEM_PROMPT_EN,
    _CHINESE_JSON_TEMPLATE_EN,
    _CHINESE_SYSTEM_PROMPT_EN,
    _KOREAN_JSON_TEMPLATE_EN,
    _KOREAN_SYSTEM_PROMPT_EN,
    _ENGLISH_JSON_TEMPLATE_EN,
    _ENGLISH_SYSTEM_PROMPT_EN,
    _SYSTEM_PROMPTS,
    _JSON_TEMPLATES,
    _SYSTEM_PROMPTS_EN,
    _JSON_TEMPLATES_EN,
    _JAPANESE_GRAMMAR_JSON_TEMPLATE,
    _JAPANESE_GRAMMAR_SYSTEM_PROMPT,
    _CHINESE_GRAMMAR_JSON_TEMPLATE,
    _CHINESE_GRAMMAR_SYSTEM_PROMPT,
    _KOREAN_GRAMMAR_JSON_TEMPLATE,
    _KOREAN_GRAMMAR_SYSTEM_PROMPT,
    _ENGLISH_GRAMMAR_JSON_TEMPLATE,
    _ENGLISH_GRAMMAR_SYSTEM_PROMPT,
    _JAPANESE_GRAMMAR_JSON_TEMPLATE_EN,
    _JAPANESE_GRAMMAR_SYSTEM_PROMPT_EN,
    _CHINESE_GRAMMAR_JSON_TEMPLATE_EN,
    _CHINESE_GRAMMAR_SYSTEM_PROMPT_EN,
    _KOREAN_GRAMMAR_JSON_TEMPLATE_EN,
    _KOREAN_GRAMMAR_SYSTEM_PROMPT_EN,
    _ENGLISH_GRAMMAR_JSON_TEMPLATE_EN,
    _ENGLISH_GRAMMAR_SYSTEM_PROMPT_EN,
    _GRAMMAR_SYSTEM_PROMPTS,
    _GRAMMAR_JSON_TEMPLATES,
    _GRAMMAR_SYSTEM_PROMPTS_EN,
    _GRAMMAR_JSON_TEMPLATES_EN,
)


__all__ = [name for name in globals() if name.startswith("_") and not name.startswith("__")]
